### ISSUE TITLE
How I solve scrambles like this?

### ISSUE THREAD

**Issue by Vivaldo-Roque** [tremwil/TwoPhaseSolver#1]
>>> import kociemba

>>> kociemba.solve('DRLUUBFBRBLURRLRUBLRDDFDLFUFUFFDBRDUBRUFLLFDDBFLUBLRBD')

u"D2 R' D' F2 B D R2 D2 R' F2 D' F2 U' B2 L2 U2 D R2 U"

**Comment by tremwil** [comment]
You would create a Move object for your move and apply it to a default cube. Then pass it to the solver. Using the second move you wrote in C#:
```cs
// create a move and apply it to a new cube
Cube c = new Move("D2 R' D' F2 B D R2 D2 R' F2 D' F2 U' B2 L2 U2 D R2 U").apply(new Cube());
// Get an algorithm of at most 22 moves that solves the cube
Move solution = Search.fullSolve(c, 22);
// print the move to the console
Console.WriteLine(solution);
```

**Comment by Vivaldo-Roque** [comment]
Thanks for the clarification.
