### ISSUE TITLE
Cube from string?

### ISSUE THREAD

**Issue by bsehovac** [tremwil/TwoPhaseSolver#3]
Is it possible to create cube from string, something like this `UUUUUUUUURRRRRRRRRFFFFFFFFFLLLLLLLLLBBBBBBBBBDDDDDDDDD`?

**Comment by tremwil** [comment]
No, but the constructor for `Cube` can take a byte array of integers determining the "colors" of the facelets, which I assume is what you asked. You could simply make a function (say, `toColorCode`) to convert your `URFLBD` codes to the correct integer values and then do 
```cs
var myCubeStr = "UUUUUUUUURRRRRRRRRFFFFFFFFFLLLLLLLLLBBBBBBBBBDDDDDDDDD";
var myCube = new Cube(myCubeStr.Select(chr => toColorCode(chr)).ToArray())
```
There are comments in `Cube.cs` that show in which order one must provide the facelets. Keep in mind that the centers should not be provided.

**Comment by bsehovac** [comment]
Thanks. I'm just gonna leave this here if anyone else need help, when describing face, use the second pattern:
```
U1 U2 U3        U1 U2 U3
U4 U5 U6   ->   U8    U4
U7 U8 U9        U7 U6 U5
```
Btw plugin is awesome, it's blazing fast for ~25 moves solutions, just what I've needed.
